/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StudentMarksCapturing;
 import javax.swing.*;
public class App {


    public static void main(String[] args) {
        
        SwingUtilities.invokeLater(() -> {
                String studentNumber = JOptionPane.showInputDialog("Enter StudentNumber");
                String name = JOptionPane.showInputDialog("Enter Name:");
                String surname = JOptionPane.showInputDialog("Enter Surname:");
                String email = JOptionPane.showInputDialog("Enter Email:");
                String phoneNumber = JOptionPane.showInputDialog("Enter Phone number:");
                int mark1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 1:"));
                int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 2:"));
                int AssignmentMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Assignment mark)"));
                int examMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Exam Mark:"));
                
                //Calculate DP status
                boolean dpStatus = ((mark1 + mark2 + AssignmentMark) / 3) >= 40;               
                //Calculate final mark
                double courseworkAverage = (mark1 + mark2 + AssignmentMark) / 3;
                double finalMark = (courseworkAverage * 0.4) + (examMark * 0.6);
                
                
                if(finalMark >= 0 && finalMark <= 46)
                {
                    JOptionPane.showInputDialog(finalMark + "% " + "You have faled");
                }
                else if(finalMark >= 47 && finalMark <= 49 )
                {
                    JOptionPane.showInputDialog(finalMark + "% " + "You need support");
                }
                else if(finalMark >=50 && finalMark <= 74 )
                {
                    JOptionPane.showInputDialog(finalMark + "% " + "You have passed");
                }
                else
                {
                    JOptionPane.showInputDialog(finalMark + "% " + "You have a distinction");
                }
                
               
                
                
                
                //Display results
                String message = "student Number: " + studentNumber + "\n"
                        + "Name: " + name + " " + surname + "\n"
                        + "Email: " + email + "\n"
                        + "Phone Number: " + phoneNumber + "\n"
                        + "Mark one: " + mark1 + "\n"
                        + "Mark two: " + mark2 + "\n"
                        + "Assignment mark: " + AssignmentMark + "\n"
                        + "Dp Status: " + (dpStatus ? "Achieved" : "Not Achieved") + "\n"
                        + "Final Mark: " + finalMark;
                JOptionPane.showMessageDialog(null, message);
        });
        
    }                    
                
    
}
            
